language: java
script: mvn install source:jar javadoc:jar -B
deploy:
  provider: releases
  api_key:
    secure: DEqnX3iaBipn+V/VlSu0KbjNziU9JadpI0WzBKzy1bJnpuzs6L1NDuAh+AgZn0q1ykocY8SQu/Zc3Vn9+bdwtM3vQmpleJf0KTTBnX+oiyMOu/mE34OIGc+p7BNaayUim5rcR0jdxSZtBiwVX3ezoJcPA3H6Ulrp3b2vs9mIkdBGEJSvC0tUklGNdPlI8BV6MrT4O7/sSiHtXX5GCibLpwjThqK9gYig4U4SqrJhfDucaTCxGUgAFFyT9SkLbAEs+IsSOHNqNOkhRgemJ6BpleLHf7cSXGYk7WdsO7y5dXle8E5sRiBXl6uKle/33D+Z9KLU+2wvEnJHhJJruTFTkwc5+ft8yBTLXOrRWUMpJ5rl8PcMdaGxYjzcQy5R89cqL0AbhdnmFuNaUgPs7OxNC1J6stgWbMfvUe7TnpQOPxUqmqyKsF8w3JQ05jWuPXpXxWiVnXasq6VI2w5GT8FGG5hoMzt89V55BSVrqqMeWGy0pzshGWasTOdJJPY6gHcwg/u3qCbJwx2QrZESqmebXcrQ+cEPmkwQdEkidQM5fTXhaNibFKSD8IrmK0Uvy183/Gpd0TIszBAdAtOC4AQOJm7/QFjureB+uoyU3sWHr9vJoBzYESj23JEr42xNZZCgyTM5F9lBTsOyStxCAqF6u4B0HY9FgvGrSWVSgqw7EY0=
  overwrite: true
  skip_cleanup: true
  file:
  - pom.xml
  - target/mongojack-2.10.0-ANONYOME-2.jar
  - target/mongojack-2.10.0-ANONYOME-2-sources.jar
  - target/mongojack-2.10.0-ANONYOME-2-javadoc.jar
  on:
    repo: anonyome/mongojack
    branch: anonyome-2.10.0
    tags: true
